### ISSUE TITLE
XIVPOTDCombo, is it being supported still?

### ISSUE THREAD

**Issue by FellCleave123** [damolitionn/MyDalamudPlugins#1]
Hey.
is XIVPOTDCOMBO still supported?
It stopped working after this latest patch. The only thing that works is barrel stabilizer 1 2 3

**Comment by damolitionn** [comment]
Wait, you were using it too? I originally made it specifically for one person so I leave it be until they request/ask me for updates.

**Comment by FellCleave123** [comment]
Yeah, it's so good and exactly what i wanted, Sloth and normal XIV combo aren't as fine tuned for POTD.
Sorry to bug you and my FC thanks you.
